// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacArchitecture
{
	public partial class TreeTableViewController : NSViewController
	{
		public TreeTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
