// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacArchitecture {
    public partial class TreeTableController : NSViewController {
        public TreeTableController(IntPtr handle) : base(handle) {
       
        }
    }
}
